[lit] Set force_execute_external to True
The LLVM patch llvm/llvm-project#203689 deprecates the use of execute_external=True in ShTest causing the following failure while running the ELD tests:

ValueError: execute_external=True is deprecated as of LLVM-23 and the option will be removed in LLVM-24. Please move to using the internal shell (execute_external=False). If you still need to force external execution to allow time for migration, set force_execute_external=True

Set force_execute_external=True until we move the ELD tests to using the internal shell.

Relevant RFC's:

https://discourse.llvm.org/t/rfc-removal-of-the-lit-external-shell/90951
https://discourse.llvm.org/t/rfc-enabling-the-lit-internal-shell-by-default/80179

Signed-off-by: Sudharsan Veeravalli <svs@qti.qualcomm.com>